# Installations

In [7]:
!pip install nvidia-cudnn-cu11==8.6.0.163 tensorflow==2.12.*

In [15]:
!pip install pandas numpy
!pip install -U scikit-learn

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.6/9.6 MB 937.3 kB/s eta 0:00:00m eta 0:00:010:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 298.0/298.0 kB 848.1 kB/s eta 0:00:00 MB/s eta 0:00:01:01
  Using cached threadpoolctl-3.1.0-py3-none-any.whl (14 kB)


# Import

In [9]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [10]:
tf.__version__

'2.12.0'

# Import data

In [39]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values 
y = dataset.iloc[:, -1].values # y values to compare

In [40]:
print(y)
print(X)

[1 0 1 ... 1 1 0]
[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


# Encoding categorical data

Encoding the "Gender" column.<br/>
From ['Male','Famele'] to [1,0]

In [41]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2]) # Only column 2 (gender)

print(X[0:4])

[[619 'France' 0 42 2 0.0 1 1 1 101348.88]
 [608 'Spain' 0 41 1 83807.86 1 0 1 112542.58]
 [502 'France' 0 42 8 159660.8 3 1 0 113931.57]
 [699 'France' 0 39 1 0.0 2 0 0 93826.63]]


One Hot Encoding the "Geography" column, the process set the encoder column (geography) first<br/>
comibation between 0s and 1s<br/>
100 => France, 001 => Spain, etc

In [42]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
# for geography column

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X[0:4])

[[1.0 0.0 0.0 619 0 42 2 0.0 1 1 1 101348.88]
 [0.0 0.0 1.0 608 0 41 1 83807.86 1 0 1 112542.58]
 [1.0 0.0 0.0 502 0 42 8 159660.8 3 1 0 113931.57]
 [1.0 0.0 0.0 699 0 39 1 0.0 2 0 0 93826.63]]


# Splitting the dataset into the Training set and Test set

In [48]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
print(X_train[0:4])
print(X_test[0:4])

[[0.0 0.0 1.0 667 0 34 5 0.0 2 1 0 163830.64]
 [0.0 1.0 0.0 427 1 42 1 75681.52 1 1 1 57098.0]
 [1.0 0.0 0.0 535 0 29 2 112367.34 1 1 0 185630.76]
 [0.0 0.0 1.0 654 1 40 5 105683.63 1 1 0 173617.09]]
[[0.0 1.0 0.0 597 0 35 8 131101.04 1 1 1 192852.67]
 [1.0 0.0 0.0 523 0 40 2 102967.41 1 1 0 128702.1]
 [0.0 0.0 1.0 706 0 42 8 95386.82 1 1 1 75732.25]
 [1.0 0.0 0.0 788 1 32 4 112079.58 1 0 0 89368.59]]


# Feature Scaling
very important for working with ANN
### StandardScaler
standardize or normalize the features or variables of a dataset<br />
```
z = (x - u) / s
```
where:

- z is the standardized value of a data point,
- x is the original value of the data point,
- u is the mean of the feature or variable,
- s is the standard deviation of the feature or variable.

In [49]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train[0:4])
print(X_test[0:4])

[[-1.01460667 -0.5698444   1.74309049  0.16958176 -1.09168714 -0.46460796
   0.00666099 -1.21571749  0.8095029   0.64259497 -1.03227043  1.10643166]
 [-1.01460667  1.75486502 -0.57369368 -2.30455945  0.91601335  0.30102557
  -1.37744033 -0.00631193 -0.92159124  0.64259497  0.9687384  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 -1.19119591 -1.09168714 -0.94312892
  -1.031415    0.57993469 -0.92159124  0.64259497 -1.03227043  1.48533467]
 [-1.01460667 -0.5698444   1.74309049  0.03556578  0.91601335  0.10961719
   0.00666099  0.47312769 -0.92159124  0.64259497 -1.03227043  1.27652776]]
[[-1.01460667  1.75486502 -0.57369368 -0.55204276 -1.09168714 -0.36890377
   1.04473698  0.8793029  -0.92159124  0.64259497  0.9687384   1.61085707]
 [ 0.98560362 -0.5698444  -0.57369368 -1.31490297 -1.09168714  0.10961719
  -1.031415    0.42972196 -0.92159124  0.64259497 -1.03227043  0.49587037]
 [-1.01460667 -0.5698444   1.74309049  0.57162971 -1.09168714  0.30102557
   1.04473698  0.30858264 -0.92

# Building the ANN

In [72]:
# initializing the ANN
ann = tf.keras.models.Sequential()

# Adding the input layer and the first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

# Adding the output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))


# Compiling the ANN & Training

- adam: very performance optimazer that can perform the Stochastic Gradient Descent
- binary_crossentropy: in this case we need binary classification (true or false)

In [73]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [75]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 2s 5ms/step - loss: 0.4366 - accuracy: 0.8030
Epoch 2/100
250/250 [==============================] - 1s 6ms/step - loss: 0.4305 - accuracy: 0.8051
Epoch 3/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4237 - accuracy: 0.8111
Epoch 4/100
250/250 [==============================] - 2s 7ms/step - loss: 0.4157 - accuracy: 0.8167
Epoch 5/100
250/250 [==============================] - 1s 6ms/step - loss: 0.4059 - accuracy: 0.8256
Epoch 6/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3953 - accuracy: 0.8346
Epoch 7/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3854 - accuracy: 0.8396
Epoch 8/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3769 - accuracy: 0.8456
Epoch 9/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3702 - accuracy: 0.8472
Epoch 10/100
250/250 [==============================] - 2s 7ms/step - loss: 0.3647 - accura

250/250 [==============================] - 1s 2ms/step - loss: 0.3343 - accuracy: 0.8634
Epoch 82/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3343 - accuracy: 0.8626
Epoch 83/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3339 - accuracy: 0.8635
Epoch 84/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3340 - accuracy: 0.8630
Epoch 85/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3348 - accuracy: 0.8637
Epoch 86/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3344 - accuracy: 0.8614
Epoch 87/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3341 - accuracy: 0.8634
Epoch 88/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3342 - accuracy: 0.8643
Epoch 89/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3338 - accuracy: 0.8616
Epoch 90/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3342 - accuracy: 

# Predicting the result

In [68]:
# predicgint only a single observation
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 91ms/step
[[False]]


In [69]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [70]:
### Metrics and accuracy

In [71]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1510   85]
 [ 199  206]]


0.858